# Generated by Django 3.2 on 2020-10-29 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0003_auto_20201023_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='buddies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_message', models.TextField()),
                ('approved', models.BooleanField()),
                ('denied_message', models.TextField()),
                ('denied', models.BooleanField()),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestee', to='userAccount.useraccount')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='userAccount.useraccount')),
            ],
        ),
    ]
