# Generated by Django 3.2 on 2020-11-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0005_auto_20201104_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
