# Generated by Django 3.1.1 on 2020-10-23 16:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0005_auto_20201022_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=112)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='userAccount.useraccount')),
            ],
        ),
    ]
