# Generated by Django 3.1.1 on 2020-10-23 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0006_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='calendar',
            field=models.CharField(max_length=112),
        ),
        migrations.AlterField(
            model_name='availability',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='userAccount.useraccount', unique=True),
        ),
    ]
