# Generated by Django 3.2 on 2020-11-23 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0008_auto_20201111_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_link', models.TextField()),
                ('passcode', models.TextField()),
                ('date', models.TextField()),
                ('buddies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddies', to='userAccount.buddies')),
            ],
        ),
    ]
