# Generated by Django 3.2 on 2020-11-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0009_zoommeeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zoommeeting',
            old_name='date',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='passcode',
        ),
    ]
