# Generated by Django 3.2 on 2020-11-23 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0009_message'),
        ('userAccount', '0010_auto_20201123_1703'),
    ]

    operations = [
    ]
